APPLICATION = lqe_broadcast
BOARD ?= iotlab-m3
RIOTBASE ?= /senslab/users/varshney/RIOT
USEMODULE += xtimer
USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_netif_single
USEMODULE += gnrc_pktbuf_static
USEMODULE += gnrc_pktdump
USEMODULE += gnrc_netreg
USEMODULE += gnrc_netapi
USEMODULE += gnrc_netif_hdr
USEMODULE += printf_float
include $(RIOTBASE)/Makefile.include
